In [9]:
#importing necessary Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import metrics

In [10]:
# Loading Data
data = pd.read_excel(r"/content/drive/MyDrive/Colab Notebooks/DecisionTree_DataSet.xlsx")
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
#copying data
df = data.copy()
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [12]:
# For Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  160 non-null    float64
 1   sepal_width   160 non-null    float64
 2   petal_length  160 non-null    float64
 3   petal_width   160 non-null    float64
 4   species       160 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.4+ KB


In [13]:
# for describing
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    160.000000   160.000000    160.000000   160.000000
mean       5.881250     3.052500      3.856875     1.259375
std        0.820123     0.424553      1.751643     0.777700
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.500000     1.400000
75%        6.500000     3.300000      5.125000     1.900000
max        7.900000     4.400000      6.900000     2.500000

In [14]:
# Setting Feature and Terget
X = df.drop(columns = ['species'],axis = 1)
y = df['species']

In [15]:
#Converting categorical "species" as Numeric
y_encoded , y_label = pd.factorize(y)
print(y_encoded)
print(y_label)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 0 0 0 0 0]
Index(['setosa', 'versicolor', 'virginica'], dtype='object')


In [16]:
#Split daset

X_train, X_test , y_train , y_test = train_test_split( X , y_encoded , test_size = 0.25 , random_state = 42)

In [17]:
# Scaling the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
#Building and Trainning Model
model = DecisionTreeClassifier()

#traning The Model
model.fit(X_train_scaled , y_train)

DecisionTreeClassifier()

In [19]:
# Prediction
y_predict = model.predict(X_test_scaled)
print(y_predict)


[2 2 2 1 1 0 2 1 2 2 0 1 0 1 0 0 2 0 1 0 1 0 0 0 0 2 1 1 2 2 2 1 1 0 0 2 0
 0 1 1]


In [20]:
# Getting back the label
y_predict_label = y_label[y_predict]
print(y_predict_label)

Index(['virginica', 'virginica', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'versicolor', 'virginica', 'virginica', 'setosa',
       'versicolor', 'setosa', 'versicolor', 'setosa', 'setosa', 'virginica',
       'setosa', 'versicolor', 'setosa', 'versicolor', 'setosa', 'setosa',
       'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'virginica', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'setosa', 'virginica', 'setosa', 'setosa', 'versicolor',
       'versicolor'],
      dtype='object')


In [22]:
#Accuracy
accuracy = metrics.accuracy_score(y_test,y_predict)
confusion = metrics.confusion_matrix(y_test,y_predict)
classification_report = metrics.classification_report(y_test , y_predict)



print(f'Accuracy : {accuracy}')
print(f'Confusion : {confusion}')
print(f'Classification Report : {classification_report}')

Accuracy : 0.95
Confusion : [[13  0  0]
 [ 0 13  0]
 [ 2  0 12]]
Classification Report :               precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      1.00      1.00        13
           2       1.00      0.86      0.92        14

    accuracy                           0.95        40
   macro avg       0.96      0.95      0.95        40
weighted avg       0.96      0.95      0.95        40



In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
#Building and Trainning Model
model = RandomForestClassifier()

#traning The Model
model.fit(X_train_scaled , y_train)

RandomForestClassifier()

In [25]:
# Prediction
y_predict = model.predict(X_test_scaled)
print(y_predict)

[2 2 2 1 1 0 2 1 2 2 0 1 0 1 0 0 2 0 1 0 1 0 0 0 0 2 1 1 2 2 2 1 1 2 0 2 0
 0 1 1]


In [26]:
# Getting back the label
y_predict_label = y_label[y_predict]
print(y_predict_label)

Index(['virginica', 'virginica', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'versicolor', 'virginica', 'virginica', 'setosa',
       'versicolor', 'setosa', 'versicolor', 'setosa', 'setosa', 'virginica',
       'setosa', 'versicolor', 'setosa', 'versicolor', 'setosa', 'setosa',
       'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'virginica', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'virginica', 'setosa', 'setosa', 'versicolor',
       'versicolor'],
      dtype='object')


In [27]:
#Accuracy
accuracy = metrics.accuracy_score(y_test,y_predict)
confusion = metrics.confusion_matrix(y_test,y_predict)
classification_report = metrics.classification_report(y_test , y_predict)



print(f'Accuracy : {accuracy}')
print(f'Confusion : {confusion}')
print(f'Classification Report : {classification_report}')

Accuracy : 0.975
Confusion : [[13  0  0]
 [ 0 13  0]
 [ 1  0 13]]
Classification Report :               precision    recall  f1-score   support

           0       0.93      1.00      0.96        13
           1       1.00      1.00      1.00        13
           2       1.00      0.93      0.96        14

    accuracy                           0.97        40
   macro avg       0.98      0.98      0.98        40
weighted avg       0.98      0.97      0.97        40



In [28]:
from sklearn.ensemble import GradientBoostingClassifier


In [29]:
#Building and Trainning Model
model = GradientBoostingClassifier()

#traning The Model
model.fit(X_train_scaled , y_train)

GradientBoostingClassifier()

In [30]:
# Prediction
y_predict = model.predict(X_test_scaled)
print(y_predict)

[2 2 2 1 1 0 2 1 2 2 0 1 0 1 0 0 2 0 1 0 1 0 0 0 0 2 1 1 2 2 2 1 1 2 0 2 0
 0 1 1]


In [31]:
# Getting back the label
y_predict_label = y_label[y_predict]
print(y_predict_label)

Index(['virginica', 'virginica', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'versicolor', 'virginica', 'virginica', 'setosa',
       'versicolor', 'setosa', 'versicolor', 'setosa', 'setosa', 'virginica',
       'setosa', 'versicolor', 'setosa', 'versicolor', 'setosa', 'setosa',
       'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'virginica', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'virginica', 'setosa', 'setosa', 'versicolor',
       'versicolor'],
      dtype='object')


In [32]:
#Accuracy
accuracy = metrics.accuracy_score(y_test,y_predict)
confusion = metrics.confusion_matrix(y_test,y_predict)
classification_report = metrics.classification_report(y_test , y_predict)



print(f'Accuracy : {accuracy}')
print(f'Confusion : {confusion}')
print(f'Classification Report : {classification_report}')

Accuracy : 0.975
Confusion : [[13  0  0]
 [ 0 13  0]
 [ 1  0 13]]
Classification Report :               precision    recall  f1-score   support

           0       0.93      1.00      0.96        13
           1       1.00      1.00      1.00        13
           2       1.00      0.93      0.96        14

    accuracy                           0.97        40
   macro avg       0.98      0.98      0.98        40
weighted avg       0.98      0.97      0.97        40

